services:
  ros2_humble:
    image: osrf/ros:humble-desktop-full
    container_name: ros2_humble_dev
    privileged: true
    environment:
      # Display forwarding
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      # Set up shared user for graphical applications
      - USER=${USER}
      - UID=${UID}
      - GID=${GID}
    volumes:
      # Mount your ROS workspace
      - ~/ros2_ws:/home/ros2_ws
      # Forward access to host's /dev
      - /dev:/dev
      # Forward the host's X11 socket for GUI applications
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    working_dir: /home/ros2_ws
    tty: true
    stdin_open: true
    restart: unless-stopped
